#!/bin/bash

cd
sudo wget https://git.io/vpn -O openvpn-install.sh
sudo chmod 755 openvpn-install.sh
sudo ./openvpn-install.sh

echo "Change the following settings"
echo "Set "
echo "Comment out the last push"
sudo nano /etc/openvpn/server/server.conf


curl -sSL https://install.pi-hole.net | bash
